Imporatnt python labraries for Machine Learning

•Install numpy, matplotlib, pandas, sklearn and their dependencies

pip install numpy
pip install scipy
pip install scikit-learn
pip install matplotlib
pip install pandas


In [2]:
from __future__ import division
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd 

In [3]:
import sys
print('Python: {}'.format(sys.version))
# scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
# numpy
import numpy
print('numpy: {}'.format(numpy.__version__))
# matplotlib
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
# pandas
import pandas
print('pandas: {}'.format(pandas.__version__))
# scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))

Python: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
scipy: 1.6.2
numpy: 1.20.1
matplotlib: 3.3.4
pandas: 1.2.4
sklearn: 0.24.1


NumPy - Numerical Python

Advantages of Numpy Arrays:

Allows several Mathematical Operations
Faster operations

In [3]:
# List vs Numpy - Time Taken
import numpy as np
from time import process_time

#Time taken by a list
python_list = [i for i in range(10000000)]

start_time = process_time()

python_list = [i+5 for i in python_list] # Add 5 with every element

end_time = process_time()
t_list=end_time - start_time

print("Time taken by list is:", t_list)

#Time taken by a Numpy
np_array = np.array([i for i in range(10000000)])

start_time = process_time()

np_array += 5  

end_time = process_time()

t_np=end_time - start_time

print("Time taken by numpy is:", t_np)


Time taken by list is: 1.328125
Time taken by numpy is: 0.015625


Numpy Arrays

In [4]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [5]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [6]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [7]:
# creating a 2 dim array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [8]:
#Define floating value array
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [11]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print('x array is')
print(x)

# create a numpy array of ones
y = np.ones((3,3))
print('y array is')
print(y)

# array of a particular value
z = np.full((5,4),1)
print('z array is')
print(z)

x array is
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
y array is
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
z array is
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.71808971 0.32763274 0.37048596 0.51486488]
 [0.14456274 0.29610847 0.16345488 0.92271556]
 [0.79442146 0.87780106 0.82569774 0.81238669]]


In [17]:
# random integer values array within a specific range
c = np.random.randint(20,1000,(4,5))
print(c)

[[400 800 975 754 924]
 [299 419 251 252  86]
 [162 537 600 146 703]
 [695  63 962 747 650]]


In [18]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [19]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [20]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [22]:
# Play with numpy array
c = np.random.randint(20,90,(4,5))
print(c)
#array dimension
print("Dimension of array c:",c.shape)
# number of dimensions
print("number of dimensions of array c:",c.ndim)
# number of elements in an array
print("number of elements of array c:",c.size)
# checking the data type of the values in the array
print(c.dtype)

[[43 70 63 60 30]
 [42 42 70 41 37]
 [65 73 24 61 38]
 [80 73 78 61 80]]
Dimension of array c: (4, 5)
number of dimensions of array c: 2
number of elements of array c: 20
int32


Mathematical operations on a np array

In [23]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [24]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print('a=',a)
print('b=',b)
print('Addition')
print(a+b)
print('Subtraction')
print(a-b)
print('Multiplication')
print(a*b)
print('Division')
print(a/b)

a= [[6 3 8]
 [7 1 6]
 [6 6 4]]
b= [[14 18 13]
 [18 11 18]
 [19 19 12]]
Addition
[[20 21 21]
 [25 12 24]
 [25 25 16]]
Subtraction
[[ -8 -15  -5]
 [-11 -10 -12]
 [-13 -13  -8]]
Multiplication
[[ 84  54 104]
 [126  11 108]
 [114 114  48]]
Division
[[0.42857143 0.16666667 0.61538462]
 [0.38888889 0.09090909 0.33333333]
 [0.31578947 0.31578947 0.33333333]]


In [25]:
#a = np.random.randint(0,10,(3,3))
#b = np.random.randint(10,20,(3,3))
print('a=',a)
print('b=',b)
print('Addition')
print(np.add(a,b))
print('Subtraction')
print(np.subtract(a,b))
print('Multiplication')
print(np.multiply(a,b))
print('Division')
print(np.divide(a,b))

a= [[6 3 8]
 [7 1 6]
 [6 6 4]]
b= [[14 18 13]
 [18 11 18]
 [19 19 12]]
Addition
[[20 21 21]
 [25 12 24]
 [25 25 16]]
Subtraction
[[ -8 -15  -5]
 [-11 -10 -12]
 [-13 -13  -8]]
Multiplication
[[ 84  54 104]
 [126  11 108]
 [114 114  48]]
Division
[[0.42857143 0.16666667 0.61538462]
 [0.38888889 0.09090909 0.33333333]
 [0.31578947 0.31578947 0.33333333]]


Array Manipulation

In [26]:
array = np.random.randint(0,20,(3,5))
print(array)
print(array.shape)

[[ 6 14 18  5  6]
 [19  0 12  9 15]
 [ 0  6 11 19  9]]
(3, 5)


In [27]:
# transpose using np.transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[ 6 19  0]
 [14  0  6]
 [18 12 11]
 [ 5  9 19]
 [ 6 15  9]]
(5, 3)


In [28]:
# transpose using .T
trans2 = array.T
print(trans2)
print(trans2.shape)

[[ 6 19  0]
 [14  0  6]
 [18 12 11]
 [ 5  9 19]
 [ 6 15  9]]
(5, 3)


In [29]:
# reshaping a array
a = np.random.randint(0,10,(4,3))
print(a)
print(a.shape)

[[9 8 7]
 [7 7 4]
 [4 8 3]
 [6 4 8]]
(4, 3)


In [30]:
b = a.reshape(3,4)
print(b)
print(b.shape)

[[9 8 7 7]
 [7 4 4 8]
 [3 6 4 8]]
(3, 4)


In [34]:
b = a.reshape(6,2)
print(b)
print(b.shape)

[[9 8]
 [7 7]
 [7 4]
 [4 8]
 [3 6]
 [4 8]]
(6, 2)
